---

#This meant to be run at the begining of each non-root playbook
# I may move this to handlers if they are more convinient

#---Container Domain---

- name: "{{ play_name }}Checking if {{ container_path }} exists"
  stat:
    path: "{{ container_path }}"
  register: check_ctr

- name: "{{ play_name }}Checking {{ container_domain }}"
  environment:
    PATH: "{{ container_path }}/bin:{{ ansible_env.PATH }}"
  command: "nohup asadmin list-domains"
  when: check_ctr.stat.exists == true
  register: check_ctr_doms

- name: "{{ play_name }}Setting conditional variable for next task"
  set_fact:
    ctr_dom: "{{ container_domain }} not running"

- name: "{{ play_name }}Starting {{ container_domain }}"
  environment:
    PATH: "{{ container_path }}/bin:{{ ansible_env.PATH }}"
  command: "nohup {{ item }}"
  with_items:
    - "asadmin start-domain {{ container_domain }}"
    - "asadmin list-domains"
  when: 
    - check_ctr.stat.exists == true
    - "ctr_dom in check_ctr_doms.stdout"

