---

#---Download Container---

- name: "{{ play_name }}Downloading and Unzipping {{ container_zip }}"
  include: "include_download.yml"
  vars:
    - download_zip: "{{ container_zip }}"
    - download_src: "{{ container_src }}"
    - download_path: "{{ container_path }}"
    - download_dest: "{{ user_home }}"

#---

#---Download Glassfish setup script---

- name: "{{ play_name }}Checking if setup-glassfish.py exists"
  stat:
    path: "{{ user_home }}/setup-glassfish.py"
  register: ctr_script

- name: "{{ play_name }}Downloading {{ container_name | title }} setup script"
  get_url:
    url: "{{ container_setup }}"
    dest: "{{ user_home }}"
  when: ctr_script.stat.exists == false

#---

#---Run Glassfish setup script---

- name: "{{ play_name }}Checking if {{ container_domain }} exists"
  stat:
    path: "{{ container_path }}/glassfish/domains/{{ container_domain }}"
  register: ctr_dom

- name: "{{ play_name }}Stopping {{ container_domain }}"
  environment:
    PATH: "{{ container_path }}/bin:{{ ansible_env.PATH }}"
  command: "nohup asadmin stop-domain {{ container_domain }}"
  when: ctr_dom.stat.exists == true

- name: "{{ play_name }}Running setup script"
  environment:
    PATH: "{{ container_path }}/bin:{{ ansible_env.PATH }}"
  command: "python {{ user_home }}/setup-glassfish.py {{ container_domain }} 75% {{ mysql_root_pass }}"
  tags:
    - install

#---

#---Configuring Domain---

- name: "{{ play_name }}Finding mysql java connector"
  find:
    paths: /usr/share/java
    patterns: 'mysql-connector-java-*.jar'
  register: sql_java

- name: "{{ play_name }}Moving Java Connector File for {{ container_domain }} and MySQL"
  copy:
    src: "{{ sql_java.files[0].path }}"
    dest: "{{ container_path }}/glassfish/domains/{{ container_domain }}/lib/ext/"
    remote_src: yes

- name: "{{ play_name }}Restarting {{ container_domain }}"
  environment:
    PATH: "{{ container_path }}/bin:{{ ansible_env.PATH }}"
  command: "nohup {{ item }}"
  with_items:
  - "asadmin restart-domain {{ container_domain }}"
  - "asadmin list-domains"
  
#---
